import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parse } from "yaml";

const root = resolve(import.meta.dirname, "..");
const catalogRoot = resolve(root, "catalog");
const manifest = JSON.parse(await readFile(resolve(catalogRoot, "manifest.json"), "utf8"));

async function assertCatalogFiles(directory, expected) {
  const actual = (await readdir(resolve(catalogRoot, directory))).filter((name) => name.endsWith(".yaml")).sort();
  const listed = expected.map((entry) => entry.file.replace(`${directory}/`, "")).sort();
  if (JSON.stringify(actual) !== JSON.stringify(listed)) {
    throw new Error(`${directory} files do not match catalog/manifest.json`);
  }
}

await assertCatalogFiles("workflows", manifest.workflows);
await assertCatalogFiles("agents", manifest.agents);

const workflows = await Promise.all(
  manifest.workflows.map(async (entry) => {
    const { file, ...definition } = entry;
    return {
      ...definition,
      yaml: await readFile(resolve(catalogRoot, file), "utf8"),
    };
  }),
);

const agents = await Promise.all(
  manifest.agents.map(async (entry) => {
    const yaml = await readFile(resolve(catalogRoot, entry.file), "utf8");
    const document = parse(yaml);
    if (document?.kind !== "AgentTemplate" || document?.metadata?.name !== entry.id) {
      throw new Error(`${entry.file} is not the expected AgentTemplate ${entry.id}`);
    }
    return {
      id: entry.id,
      path: document.spec.path,
      name: document.metadata.title,
      role: document.spec.role,
      prompt: document.spec.prompt,
      skills: document.spec.capabilities?.skills ?? [],
      tools: document.spec.capabilities?.tools ?? [],
      connectors: document.spec.capabilities?.connectors ?? [],
      permissions: document.spec.capabilities?.permissions ?? ["read-only"],
    };
  }),
);

const blankWorkflow = await readFile(resolve(catalogRoot, "blank-workflow.yaml"), "utf8");
const source = `// Generated by scripts/generate-catalog-index.mjs. Do not edit.\nimport type { RoleTemplate, TemplateDefinition } from "../types";\n\nexport const BLANK_WORKFLOW = ${JSON.stringify(blankWorkflow)};\n\nexport const WORKFLOW_TEMPLATES: TemplateDefinition[] = ${JSON.stringify(workflows, null, 2)};\n\nexport const ROLE_TEMPLATES: RoleTemplate[] = ${JSON.stringify(agents, null, 2)};\n`;
await mkdir(resolve(root, "src/generated"), { recursive: true });
await writeFile(resolve(root, "src/generated/catalog.ts"), source);
console.log(`Generated browser index for ${workflows.length} workflows and ${agents.length} agent templates.`);
